export const SET_CLOTHES = 'SET_CLOTHES';
export const SET_PRODUCTS_FAILED = 'SET_PRODUCTS_FAILED';
export const SET_FLOAT_GALLERY_MODELS = 'SET_FLOAT_GALLERY_MODELS';
export const SET_FLOAT_GALLERY_MODELS_FAILED = 'SET_FLOAT_GALLERY_MODELS_FAILED';
export const SET_FRONT_PAGE_CONTENT = 'SET_FRONT_PAGE_CONTENT';